apiVersion: v1
kind: Service
metadata:
  name: uts-devops-service
  namespace: default
  labels:
    app: uts-devops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: uts-devops